<?php

use Illuminate\Database\Seeder;

class AuthRulesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('auth_rules')->delete();
        
        \DB::table('auth_rules')->insert(array (
            0 => 
            array (
                'id' => 1,
                'type' => 'file',
                'pid' => 0,
                'name' => 'dashboard',
                'title' => 'Dashboard',
                'icon' => 'fa fa-dashboard',
                'condition' => '',
                'remark' => 'Dashboard tips',
                'ismenu' => 1,
                'weigh' => 143,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            1 => 
            array (
                'id' => 2,
                'type' => 'file',
                'pid' => 0,
                'name' => 'general',
                'title' => 'General',
                'icon' => 'fa fa-cogs',
                'condition' => '',
                'remark' => '',
                'ismenu' => 1,
                'weigh' => 137,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            2 => 
            array (
                'id' => 3,
                'type' => 'file',
                'pid' => 0,
                'name' => 'category',
                'title' => 'Category',
                'icon' => 'fa fa-leaf',
                'condition' => '',
                'remark' => 'Category tips',
                'ismenu' => 1,
                'weigh' => 119,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            3 => 
            array (
                'id' => 4,
                'type' => 'file',
                'pid' => 0,
                'name' => 'addon',
                'title' => 'Addon',
                'icon' => 'fa fa-rocket',
                'condition' => '',
                'remark' => 'Addon tips',
                'ismenu' => 1,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            4 => 
            array (
                'id' => 5,
                'type' => 'file',
                'pid' => 0,
                'name' => 'auth',
                'title' => 'Auth',
                'icon' => 'fa fa-group',
                'condition' => '',
                'remark' => '',
                'ismenu' => 1,
                'weigh' => 99,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            5 => 
            array (
                'id' => 6,
                'type' => 'file',
                'pid' => 2,
                'name' => 'general/config',
                'title' => 'Config',
                'icon' => 'fa fa-cog',
                'condition' => '',
                'remark' => 'Config tips',
                'ismenu' => 1,
                'weigh' => 60,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            6 => 
            array (
                'id' => 7,
                'type' => 'file',
                'pid' => 2,
                'name' => 'general/attachment',
                'title' => 'Attachment',
                'icon' => 'fa fa-file-image-o',
                'condition' => '',
                'remark' => 'Attachment tips',
                'ismenu' => 1,
                'weigh' => 53,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            7 => 
            array (
                'id' => 8,
                'type' => 'file',
                'pid' => 2,
                'name' => 'general/profile',
                'title' => 'Profile',
                'icon' => 'fa fa-user',
                'condition' => '',
                'remark' => '',
                'ismenu' => 1,
                'weigh' => 34,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            8 => 
            array (
                'id' => 9,
                'type' => 'file',
                'pid' => 5,
                'name' => 'auth/admin',
                'title' => 'Admin',
                'icon' => 'fa fa-user',
                'condition' => '',
                'remark' => 'Admin tips',
                'ismenu' => 1,
                'weigh' => 118,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            9 => 
            array (
                'id' => 10,
                'type' => 'file',
                'pid' => 5,
                'name' => 'auth/adminlog',
                'title' => 'Admin log',
                'icon' => 'fa fa-list-alt',
                'condition' => '',
                'remark' => 'Admin log tips',
                'ismenu' => 1,
                'weigh' => 113,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            10 => 
            array (
                'id' => 11,
                'type' => 'file',
                'pid' => 5,
                'name' => 'auth/group',
                'title' => 'Group',
                'icon' => 'fa fa-group',
                'condition' => '',
                'remark' => 'Group tips',
                'ismenu' => 1,
                'weigh' => 109,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            11 => 
            array (
                'id' => 12,
                'type' => 'file',
                'pid' => 5,
                'name' => 'auth/rule',
                'title' => 'Rule',
                'icon' => 'fa fa-bars',
                'condition' => '',
                'remark' => 'Rule tips',
                'ismenu' => 1,
                'weigh' => 104,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            12 => 
            array (
                'id' => 13,
                'type' => 'file',
                'pid' => 1,
                'name' => 'dashboard/index',
                'title' => 'View',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 136,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            13 => 
            array (
                'id' => 14,
                'type' => 'file',
                'pid' => 1,
                'name' => 'dashboard/add',
                'title' => 'Add',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 135,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            14 => 
            array (
                'id' => 15,
                'type' => 'file',
                'pid' => 1,
                'name' => 'dashboard/del',
                'title' => 'Delete',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 133,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            15 => 
            array (
                'id' => 16,
                'type' => 'file',
                'pid' => 1,
                'name' => 'dashboard/edit',
                'title' => 'Edit',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 134,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            16 => 
            array (
                'id' => 17,
                'type' => 'file',
                'pid' => 1,
                'name' => 'dashboard/multi',
                'title' => 'Multi',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 132,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            17 => 
            array (
                'id' => 18,
                'type' => 'file',
                'pid' => 6,
                'name' => 'general/config/index',
                'title' => 'View',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 52,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            18 => 
            array (
                'id' => 19,
                'type' => 'file',
                'pid' => 6,
                'name' => 'general/config/add',
                'title' => 'Add',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 51,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            19 => 
            array (
                'id' => 20,
                'type' => 'file',
                'pid' => 6,
                'name' => 'general/config/edit',
                'title' => 'Edit',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 50,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            20 => 
            array (
                'id' => 21,
                'type' => 'file',
                'pid' => 6,
                'name' => 'general/config/del',
                'title' => 'Delete',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 49,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            21 => 
            array (
                'id' => 22,
                'type' => 'file',
                'pid' => 6,
                'name' => 'general/config/multi',
                'title' => 'Multi',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 48,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            22 => 
            array (
                'id' => 23,
                'type' => 'file',
                'pid' => 7,
                'name' => 'general/attachment/index',
                'title' => 'View',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => 'Attachment tips',
                'ismenu' => 0,
                'weigh' => 59,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            23 => 
            array (
                'id' => 24,
                'type' => 'file',
                'pid' => 7,
                'name' => 'general/attachment/select',
                'title' => 'Select attachment',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 58,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            24 => 
            array (
                'id' => 25,
                'type' => 'file',
                'pid' => 7,
                'name' => 'general/attachment/add',
                'title' => 'Add',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 57,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            25 => 
            array (
                'id' => 26,
                'type' => 'file',
                'pid' => 7,
                'name' => 'general/attachment/edit',
                'title' => 'Edit',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 56,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            26 => 
            array (
                'id' => 27,
                'type' => 'file',
                'pid' => 7,
                'name' => 'general/attachment/del',
                'title' => 'Delete',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 55,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            27 => 
            array (
                'id' => 28,
                'type' => 'file',
                'pid' => 7,
                'name' => 'general/attachment/multi',
                'title' => 'Multi',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 54,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            28 => 
            array (
                'id' => 29,
                'type' => 'file',
                'pid' => 8,
                'name' => 'general/profile/index',
                'title' => 'View',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 33,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            29 => 
            array (
                'id' => 30,
                'type' => 'file',
                'pid' => 8,
                'name' => 'general/profile/update',
                'title' => 'Update profile',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 32,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            30 => 
            array (
                'id' => 31,
                'type' => 'file',
                'pid' => 8,
                'name' => 'general/profile/add',
                'title' => 'Add',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 31,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            31 => 
            array (
                'id' => 32,
                'type' => 'file',
                'pid' => 8,
                'name' => 'general/profile/edit',
                'title' => 'Edit',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 30,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            32 => 
            array (
                'id' => 33,
                'type' => 'file',
                'pid' => 8,
                'name' => 'general/profile/del',
                'title' => 'Delete',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 29,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            33 => 
            array (
                'id' => 34,
                'type' => 'file',
                'pid' => 8,
                'name' => 'general/profile/multi',
                'title' => 'Multi',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 28,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            34 => 
            array (
                'id' => 35,
                'type' => 'file',
                'pid' => 3,
                'name' => 'category/index',
                'title' => 'View',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => 'Category tips',
                'ismenu' => 0,
                'weigh' => 142,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            35 => 
            array (
                'id' => 36,
                'type' => 'file',
                'pid' => 3,
                'name' => 'category/add',
                'title' => 'Add',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 141,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            36 => 
            array (
                'id' => 37,
                'type' => 'file',
                'pid' => 3,
                'name' => 'category/edit',
                'title' => 'Edit',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 140,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            37 => 
            array (
                'id' => 38,
                'type' => 'file',
                'pid' => 3,
                'name' => 'category/del',
                'title' => 'Delete',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 139,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            38 => 
            array (
                'id' => 39,
                'type' => 'file',
                'pid' => 3,
                'name' => 'category/multi',
                'title' => 'Multi',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 138,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            39 => 
            array (
                'id' => 40,
                'type' => 'file',
                'pid' => 9,
                'name' => 'auth/admin/index',
                'title' => 'View',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => 'Admin tips',
                'ismenu' => 0,
                'weigh' => 117,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            40 => 
            array (
                'id' => 41,
                'type' => 'file',
                'pid' => 9,
                'name' => 'auth/admin/add',
                'title' => 'Add',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 116,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            41 => 
            array (
                'id' => 42,
                'type' => 'file',
                'pid' => 9,
                'name' => 'auth/admin/edit',
                'title' => 'Edit',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 115,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            42 => 
            array (
                'id' => 43,
                'type' => 'file',
                'pid' => 9,
                'name' => 'auth/admin/del',
                'title' => 'Delete',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 114,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            43 => 
            array (
                'id' => 44,
                'type' => 'file',
                'pid' => 10,
                'name' => 'auth/adminlog/index',
                'title' => 'View',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => 'Admin log tips',
                'ismenu' => 0,
                'weigh' => 112,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            44 => 
            array (
                'id' => 45,
                'type' => 'file',
                'pid' => 10,
                'name' => 'auth/adminlog/detail',
                'title' => 'Detail',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 111,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            45 => 
            array (
                'id' => 46,
                'type' => 'file',
                'pid' => 10,
                'name' => 'auth/adminlog/del',
                'title' => 'Delete',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 110,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            46 => 
            array (
                'id' => 47,
                'type' => 'file',
                'pid' => 11,
                'name' => 'auth/group/index',
                'title' => 'View',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => 'Group tips',
                'ismenu' => 0,
                'weigh' => 108,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            47 => 
            array (
                'id' => 48,
                'type' => 'file',
                'pid' => 11,
                'name' => 'auth/group/add',
                'title' => 'Add',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 107,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            48 => 
            array (
                'id' => 49,
                'type' => 'file',
                'pid' => 11,
                'name' => 'auth/group/edit',
                'title' => 'Edit',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 106,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            49 => 
            array (
                'id' => 50,
                'type' => 'file',
                'pid' => 11,
                'name' => 'auth/group/del',
                'title' => 'Delete',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 105,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            50 => 
            array (
                'id' => 51,
                'type' => 'file',
                'pid' => 12,
                'name' => 'auth/rule/index',
                'title' => 'View',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => 'Rule tips',
                'ismenu' => 0,
                'weigh' => 103,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            51 => 
            array (
                'id' => 52,
                'type' => 'file',
                'pid' => 12,
                'name' => 'auth/rule/add',
                'title' => 'Add',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 102,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            52 => 
            array (
                'id' => 53,
                'type' => 'file',
                'pid' => 12,
                'name' => 'auth/rule/edit',
                'title' => 'Edit',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 101,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            53 => 
            array (
                'id' => 54,
                'type' => 'file',
                'pid' => 12,
                'name' => 'auth/rule/del',
                'title' => 'Delete',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 100,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            54 => 
            array (
                'id' => 55,
                'type' => 'file',
                'pid' => 4,
                'name' => 'addon/index',
                'title' => 'View',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => 'Addon tips',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            55 => 
            array (
                'id' => 56,
                'type' => 'file',
                'pid' => 4,
                'name' => 'addon/add',
                'title' => 'Add',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            56 => 
            array (
                'id' => 57,
                'type' => 'file',
                'pid' => 4,
                'name' => 'addon/edit',
                'title' => 'Edit',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            57 => 
            array (
                'id' => 58,
                'type' => 'file',
                'pid' => 4,
                'name' => 'addon/del',
                'title' => 'Delete',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            58 => 
            array (
                'id' => 59,
                'type' => 'file',
                'pid' => 4,
                'name' => 'addon/local',
                'title' => 'Local install',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            59 => 
            array (
                'id' => 60,
                'type' => 'file',
                'pid' => 4,
                'name' => 'addon/state',
                'title' => 'Update state',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            60 => 
            array (
                'id' => 61,
                'type' => 'file',
                'pid' => 4,
                'name' => 'addon/install',
                'title' => 'Install',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            61 => 
            array (
                'id' => 62,
                'type' => 'file',
                'pid' => 4,
                'name' => 'addon/uninstall',
                'title' => 'Uninstall',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            62 => 
            array (
                'id' => 63,
                'type' => 'file',
                'pid' => 4,
                'name' => 'addon/config',
                'title' => 'Setting',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            63 => 
            array (
                'id' => 64,
                'type' => 'file',
                'pid' => 4,
                'name' => 'addon/refresh',
                'title' => 'Refresh',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            64 => 
            array (
                'id' => 65,
                'type' => 'file',
                'pid' => 4,
                'name' => 'addon/multi',
                'title' => 'Multi',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            65 => 
            array (
                'id' => 66,
                'type' => 'file',
                'pid' => 0,
                'name' => 'user',
                'title' => 'User',
                'icon' => 'fa fa-list',
                'condition' => '',
                'remark' => '',
                'ismenu' => 1,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            66 => 
            array (
                'id' => 67,
                'type' => 'file',
                'pid' => 66,
                'name' => 'user/user',
                'title' => 'User',
                'icon' => 'fa fa-user',
                'condition' => '',
                'remark' => '',
                'ismenu' => 1,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            67 => 
            array (
                'id' => 68,
                'type' => 'file',
                'pid' => 67,
                'name' => 'user/user/index',
                'title' => 'View',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            68 => 
            array (
                'id' => 69,
                'type' => 'file',
                'pid' => 67,
                'name' => 'user/user/edit',
                'title' => 'Edit',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            69 => 
            array (
                'id' => 70,
                'type' => 'file',
                'pid' => 67,
                'name' => 'user/user/add',
                'title' => 'Add',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            70 => 
            array (
                'id' => 71,
                'type' => 'file',
                'pid' => 67,
                'name' => 'user/user/del',
                'title' => 'Del',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            71 => 
            array (
                'id' => 72,
                'type' => 'file',
                'pid' => 67,
                'name' => 'user/user/multi',
                'title' => 'Multi',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            72 => 
            array (
                'id' => 73,
                'type' => 'file',
                'pid' => 66,
                'name' => 'user/group',
                'title' => 'User group',
                'icon' => 'fa fa-users',
                'condition' => '',
                'remark' => '',
                'ismenu' => 1,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            73 => 
            array (
                'id' => 74,
                'type' => 'file',
                'pid' => 73,
                'name' => 'user/group/add',
                'title' => 'Add',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            74 => 
            array (
                'id' => 75,
                'type' => 'file',
                'pid' => 73,
                'name' => 'user/group/edit',
                'title' => 'Edit',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            75 => 
            array (
                'id' => 76,
                'type' => 'file',
                'pid' => 73,
                'name' => 'user/group/index',
                'title' => 'View',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            76 => 
            array (
                'id' => 77,
                'type' => 'file',
                'pid' => 73,
                'name' => 'user/group/del',
                'title' => 'Del',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            77 => 
            array (
                'id' => 78,
                'type' => 'file',
                'pid' => 73,
                'name' => 'user/group/multi',
                'title' => 'Multi',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            78 => 
            array (
                'id' => 79,
                'type' => 'file',
                'pid' => 66,
                'name' => 'user/rule',
                'title' => 'User rule',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 1,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            79 => 
            array (
                'id' => 80,
                'type' => 'file',
                'pid' => 79,
                'name' => 'user/rule/index',
                'title' => 'View',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            80 => 
            array (
                'id' => 81,
                'type' => 'file',
                'pid' => 79,
                'name' => 'user/rule/del',
                'title' => 'Del',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            81 => 
            array (
                'id' => 82,
                'type' => 'file',
                'pid' => 79,
                'name' => 'user/rule/add',
                'title' => 'Add',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            82 => 
            array (
                'id' => 83,
                'type' => 'file',
                'pid' => 79,
                'name' => 'user/rule/edit',
                'title' => 'Edit',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            83 => 
            array (
                'id' => 84,
                'type' => 'file',
                'pid' => 79,
                'name' => 'user/rule/multi',
                'title' => 'Multi',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            84 => 
            array (
                'id' => 85,
                'type' => 'file',
                'pid' => 0,
                'name' => 'command',
                'title' => '在线命令管理',
                'icon' => 'fa fa-terminal',
                'condition' => '',
                'remark' => '',
                'ismenu' => 1,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            85 => 
            array (
                'id' => 86,
                'type' => 'file',
                'pid' => 85,
                'name' => 'command/index',
                'title' => '查看',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            86 => 
            array (
                'id' => 87,
                'type' => 'file',
                'pid' => 85,
                'name' => 'command/add',
                'title' => '添加',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            87 => 
            array (
                'id' => 88,
                'type' => 'file',
                'pid' => 85,
                'name' => 'command/detail',
                'title' => '详情',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            88 => 
            array (
                'id' => 89,
                'type' => 'file',
                'pid' => 85,
                'name' => 'command/execute',
                'title' => '运行',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            89 => 
            array (
                'id' => 90,
                'type' => 'file',
                'pid' => 85,
                'name' => 'command/del',
                'title' => '删除',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
            90 => 
            array (
                'id' => 91,
                'type' => 'file',
                'pid' => 85,
                'name' => 'command/multi',
                'title' => '批量更新',
                'icon' => 'fa fa-circle-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'weigh' => 0,
                'status' => 'normal',
                'created_at' => '2020-07-08 01:28:51',
                'updated_at' => '2020-07-08 01:28:51',
            ),
        ));
        
        
    }
}