<?php
/**
 * Created by PhpStorm.
 * User: zhoulongtao
 * Date: 2020-10-03
 * Time: 11:46
 */

namespace App\Modules\Admin\Http\Controllers;


use App\Modules\Common\Controllers\BackendController;
use App\Modules\Common\Library\Tree;
use App\Modules\Model\AuthRule;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class RuleController extends BackendController
{
    protected $rulelist = [];
    protected $multiFields = 'ismenu,status';


    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->model = new AuthRule();
        // 必须将结果集转换为数组
        $ruleList = $this->model->orderBy('weigh', 'desc')->orderBy('id', 'asc')->get()->toArray();
        foreach ($ruleList as $k => &$v) {
            $v['title']  = lang($v['title']);
            $v['remark'] = lang($v['remark']);
        }
        unset($v);
        Tree::instance()->init($ruleList);
        $this->rulelist = Tree::instance()->getTreeList(Tree::instance()->getTreeArray(0), 'title');
        $ruledata       = [0 => __('None')];
        foreach ($this->rulelist as $k => &$v) {
            if (!$v['ismenu']) {
                continue;
            }
            $ruledata[$v['id']] = $v['title'];
        }
        unset($v);
        $this->assign('ruledata', $ruledata);

    }

    public function index(Request $request)
    {
        if ($request->isAjax()) {
            $list   = $this->rulelist;
            $total  = count($this->rulelist);
            $result = array("total" => $total, "rows" => $list);
            $this->json($result);
        }
        return $this->view();
    }

    public function add(Request $request)
    {
        if ($request->isMethod('post')) {
            $params = $request->post("row", []);
            if ($params) {
                if (!$params['ismenu'] && !$params['pid']) {
                    $this->error(lang('The non-menu rule must have parent'));
                }
                $this->Validator($params, [
                        'name'  => 'required|unique:auth_rules',
                        'title' => 'required',
                    ]
                );
                $result = $this->model->insert($params);
                if ($result === false) {
                    $this->error();
                }
                Cache::forget('__menu__');
                $this->success();
            }
            $this->error();
        }
        return $this->view();
    }

    public function edit(Request $request)
    {
        $ids = $request->get('ids');
        $row = $this->model->where('id', $ids)->first();
        if (!$row) {
            $this->error(lang('No Results were found'));
        }
        if ($request->isMethod('post')) {
            $params = $request->post("row");
            if ($params) {
                if (!$params['ismenu'] && !$params['pid']) {
                    $this->error(lang('The non-menu rule must have parent'));
                }
                if ($params['pid'] != $row['pid']) {
                    $childrenIds = Tree::instance()->init(AuthRule::get()->toArray())->getChildrenIds($row['id']);
                    if (in_array($params['pid'], $childrenIds)) {
                        $this->error(lang('Can not change the parent to child'));
                    }
                }
                //这里需要针对name做唯一验证
                $this->Validator($params, [
                    'name' => 'required|unique:auth_rules,name,' . $row->id,
                ]);
                $result = $this->model->where('id', $row->id)->update($params);
                if ($result === false) {
                    $this->error();
                }
                Cache::forget('__menu__');
                $this->success();
            }
            $this->error();
        }
        $this->assign("row", $row);
        return $this->view();
    }

    public function del(Request $request)
    {
        $ids = $request->get('ids');
        if ($ids) {
            $delIds = [];
            foreach (explode(',', $ids) as $k => $v) {
                $delIds = array_merge($delIds, Tree::instance()->getChildrenIds($v, true));
            }
            $delIds = array_unique($delIds);
            $count  = $this->model->whereIn('id', $delIds)->delete();
            if ($count) {
                Cache::forget('__menu__');
                $this->success();
            }
        }
        $this->error();
    }

    public function multi(Request $request)
    {


    }
}